package:
  name: apache-beam-python-3.11-sdk
  version: 2.57.0
  epoch: 0
  description: Apache Beam Python SDK
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - geos-dev
      - google-cloud-sdk
      - openjdk-17-default-jvm
      - python-3.11
      - snappy-dev
      - yaml-dev

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - gcc-12-default
      - go
      - openjdk-17
      - openjdk-17-default-jvm
      - py3.11-pip
      - python-3.11
      - python-3.11-dev
  environment:
    JAVA_HOME: /usr/lib/jvm/java-17-openjdk

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/apache/beam
      expected-commit: e3314d4c942d6fb7c9669e7eb98c5e526b83e1aa
      tag: v${{package.version}}

  # Since we can't install multiple versions of Python at the same time, and their build system
  # uses the Python 3.8 while issuing `setupVirtualenv`, this is a hacky-fix to make it work.
  - runs: ln -sf /usr/bin/python /usr/bin/python3.8

  - runs: |
      ./gradlew :sdks:python:container:py311:generatePythonRequirements
      ./gradlew :sdks:python:container:goBuild

  - runs: |
      pip install --no-deps -v sdks/python/build/apache-beam.tar.gz

      _arch=$(uname -m); case $_arch in aarch64) _arch="arm64" ;; x86_64) _arch="amd64" ;; esac
      install -D -m 755 sdks/python/container/build/target/launcher/linux_$_arch/boot /usr/bin/boot

subpackages:
  - name: "${{package.name}}-compat"
    description: "Compatibility package to place binaries in the location expected by upstream Dockerfile"
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"/opt/apache/beam
          ln -sf /usr/bin/boot ${{targets.contextdir}}/opt/apache/beam/boot

update:
  enabled: true
  ignore-regex-patterns:
    - sdks/
  github:
    identifier: apache/beam
    strip-prefix: v
    use-tag: true
